[class1]
"responsibility" = "collaborator"
"store some data" = "le_database \n asdsad \n sadsad"
"veeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrryloooooooooooooong"="dsa \n sad"
[class2]
"tell a joke"="some joke class"
"r"="c"