[class1]
"responsibility" = "collaborator"
"store some data" = "le_database \n asdsad \n sadsad"
"take some trash get out and buy food home"="trashcan \n money \n food"
[class2]
"tell a joke"="some joke class"
"r"="c"